services:
  redis:
    image: eqalpha/keydb:${SOFTWARE_VERSION_TAG}
    command: keydb-server /etc/keydb/keydb.conf --port 6379 --requirepass ${SOFTWARE_PASSWORD} ${CLUSTER_OPTIONS} #--tls-port 6380 --port 6379 --tls-ca-cert-file /data/ca.crt --tls-cert-file /data/redis.crt --tls-key-file /data/redis.key
    shm_size: "1g"
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./keydb.conf:/etc/keydb/keydb.conf
    restart: always
    ports:
      - "23647:6379"
      - "6380:6380"

  redisinsight:
    image: redislabs/redisinsight:1.12.0
    restart: always
    ports:
      - "172.17.0.1:8001:8001"
    volumes:
      - ./insight:/db
